import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        /* ── Semantic tokens (CSS-variable driven) ── */
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        /* ── Brand palette (use directly: bg-baltic-blue-500) ── */
        "baltic-blue": {
          "50":  "#e6f7fe",
          "100": "#cef0fd",
          "200": "#9de1fb",
          "300": "#6bd1fa",
          "400": "#3ac2f8",
          "500": "#09b3f6",
          "600": "#078fc5",
          "700": "#056b94",
          "800": "#044862",
          "900": "#022431",
          "950": "#011922",
        },
        teal: {
          "50":  "#e6fcff",
          "100": "#cdf8fe",
          "200": "#9bf2fd",
          "300": "#68ebfd",
          "400": "#36e5fc",
          "500": "#04defb",
          "600": "#03b2c9",
          "700": "#028597",
          "800": "#025964",
          "900": "#012c32",
          "950": "#011f23",
        },
        verdigris: {
          "50":  "#e5fffc",
          "100": "#ccfffa",
          "200": "#99fff5",
          "300": "#66fff0",
          "400": "#33ffeb",
          "500": "#00ffe6",
          "600": "#00ccb8",
          "700": "#00998a",
          "800": "#00665c",
          "900": "#00332e",
          "950": "#002420",
        },
        "mint-leaf": {
          "50":  "#e6fff9",
          "100": "#cdfef4",
          "200": "#9afee8",
          "300": "#68fddd",
          "400": "#35fdd2",
          "500": "#03fcc6",
          "600": "#02ca9f",
          "700": "#029777",
          "800": "#01654f",
          "900": "#013228",
          "950": "#00231c",
        },
        cream: {
          "50":  "#fafbe9",
          "100": "#f5f7d4",
          "200": "#ecefa9",
          "300": "#e2e77e",
          "400": "#d8df53",
          "500": "#cfd728",
          "600": "#a5ac20",
          "700": "#7c8118",
          "800": "#535610",
          "900": "#292b08",
          "950": "#1d1e06",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
